### PR TITLE
Add CloneDeploy plugin

### PR DESCRIPTION
**Pull request by cdadmin**

### CODE REVIEW

**Comment by cdadmin** [comment]
Is there anything I can do to assist with getting this approved?

**Comment by miwi-fbsd** [comment]
@cdadmin sorry for the delay. We are restructuring the iocage plugins, I will get back to it once we are done. 

Thanks.

**Comment by jed-frey** [comment]
Could you elaborate on the 'restructuring' so that people *trying* to develop for FreeNAS can wait until things are finally stable?

**Comment by cdadmin** [comment]
Please disregard this request.

**Pull request closed without merging**
