### PR TITLE
Update MinIO logo to the official "Bird" one

### PR DESCRIPTION
**Pull request by justinclift**
As per the official MinIO logo guidelines, this is the red bird logo, resized to 128px width:

&nbsp; &nbsp; https://min.io/logo

Mainly did this after noticing the current MinIO logo in the TrueNAS plugins doesn't have a background alpha channel, so looks a bit dodgy for an "official" plugin. :wink:

### CODE REVIEW

**Review by kmoore134 — APPROVED** [review]

**Comment by justinclift** [comment]
Hmmm, https://www.trueos.org/iocage-icons/minio.png is still showing the old icon.  Is there another step which needs to be done, or did I just pick the wrong repo to update? :smile:

**Comment by kmoore134** [comment]
You used the right place, probably our script broke which updates files on the web-server. Looking into it now.

**Comment by kmoore134** [comment]
Ok, should be fixed now. Thanks for letting us know.

**Comment by justinclift** [comment]
No worries at all.  The updated logo even looks decent in the TrueNAS list now too. :smile:

**Pull request merged**
