### PR TITLE
Add OpenVPN server plugin

### PR DESCRIPTION
**Pull request by gitbulb**
Would like to add a plugin for OpenVPN server.

Repository of the artifact: https://github.com/gitbulb/iocage-plugin-openvpn

Any and all comments are welcome 😃 .

### CODE REVIEW

**Comment by skarekrow** [comment]
Does OpenVPN not want the iocage `allow_tuns` parameter as well?

**Comment by gitbulb** [comment]
"Not on my development system" ™️ 😄 

I ran several jail installs during development, multiple at the same time, and apparent it didn't need it on my system. But perhaps my jail environment is to permissive? Not that I made any custom changes, as far as I can recall. 

But if you want @skarekrow , I can add it?

**Comment by skarekrow** [comment]
:D Yeah I think it would be useful here, along with looking at the repo of yours, we should be echo'ing some of those messages at the end that are important. Like the default networks, fqdn and even where they can change the files.

**Comment by gitbulb** [comment]
Sure, will add it.

Stuff like networks, fqdn and so on can be set using the properties, is that not the way to go?
That is all documented in the [README](https://github.com/gitbulb/iocage-plugin-openvpn/blob/master/README.md)

**Comment by skarekrow** [comment]
No that is the right way to go, but users need to be aware that they should do that out of the box. There will be many who don't read the README or just simply forget later on. Think of pkg messages you get when you install one, sometimes it helps :)

**Comment by gitbulb** [comment]
Something like this:
```

The following (default) setting have been used:
server_local_port=1194
server_port_type=udp
private_network==192.168.1.0 255.255.255.0
nat_network_cidr=10.8.0.0/24
nat_network=10.8.0.0 255.255.255.0
server_fqdn=nas.mydomain.com
server_public_port=443

OpenVPN server should now be running on server_port_type udp server_local_port 1194
It will provide access for remote clients to your local network (private_network): 192.168.1.0 255.255.255.0

An intermediate network is used by the client behind a NAT translation (nat_network_cidr/nat_network): 10.8.0.0/24 / 10.8.0.0 255.255.255.0
This should NOT overlap with your private network.

Client configurations which will be created will have them connect to (server_fqdn): nas.mydomain.com
Clients will connect on server_port_type udp, server_public_port: 443
You need to configure port-forwarding at the firewall in front of the OpenVPN jail to forward  udp/443 to this Jail at udp/1194

Client generation/configuration can be done using iocage:
 E.g.    iocage set -P addclient=yourclientname,somesecurecertpassphrase orac.lan
This will create a configuration folder at /usr/local/etc/openvpn/clients

By current default it will connect to server_fqdn nas.mydomain.com, server_port_type udp/server_public_port 443
To override this at generation:
E.g.    iocage set -P addclient=yourclientname,somesecurecertpassphrase,your.server.fqdn.com,444 orac.lan

For changing and applying server attributes, use iocage as well. Please consult the README for this.

```
Or too much?

**Comment by skarekrow** [comment]
Looks good to me, it's a lot of text but it's all relevant imo. I see some spacing issues:

Extra space in front of E.g.
---
```
Client generation/configuration can be done using iocage:
 E.g.
```
2 spaces
---
```forward  udp/44```

**Comment by gitbulb** [comment]
Regarding the `allow_tun` this is something added to iocage master about 14 days ago?

My current FreeNAS (11.2-Stable) does not accept that parameter and breaks the deployment.

Perhaps better to wait for that iocage change to reach FreeNAS stable release before adding it to this plugin? Or else the plugin may not be of (easy) use until then?

**Comment by skarekrow** [comment]
We can look at adding it later then if it turns out it's required :)

**Comment by skarekrow** [comment]
Thanks @gitbulb!

**Pull request merged**
