### PR TITLE
Normalize pkg entries

### PR DESCRIPTION
**Pull request by sonicaj**
This PR aims to normalize how we install pkgs. Right now we use pkg origin's to install/identify packages. Now that is misleading at best, this PR changes that and we now use pkg names instead of origin to install/identify pkgs.

### CODE REVIEW

**Comment by skarekrow** [comment]
I don't understand the need?

**Comment by william-gr** [comment]
We deal with packages, not ports. We should be using pkg names, not port origins. Origin can be ambiguous since it can provide multiple different packages.

**Comment by miwi-fbsd** [comment]
It was not working without ports category.

**Comment by sonicaj** [comment]
@miwi-fbsd which plugin ?

**Comment by william-gr** [comment]
Oh and also, using pkg names may likely avoid us having to fetch packagesite.txz for every repo.

**Comment by miwi-fbsd** [comment]
@sonicaj last time i tested it was with dnsmaq.

**Comment by sonicaj** [comment]
@miwi-fbsd it is working with `dnsmasq`, please let me know if you think there might be other potential conflicts ?

**Pull request merged**
