### PR TITLE
Add Dnsmasq SVG logo

### PR DESCRIPTION
**Pull request by justinclift**
Note that this PR only adds the SVG file (so far), and doesn't remove the existing PNG.

That's because I've not (yet) located where the logo file is specified (and would need adjusting). :wink:

* It doesn't appear to be in this repo
* It doesn't appear to be in @timsavage's [dnsmasq plugin repo](https://github.com/timsavage/iocage-plugin-dnsmasq)

Anyone able to shed light?

### CODE REVIEW

**Comment by kmoore134** [comment]
It is in this repo:

https://github.com/ix-plugin-hub/iocage-plugin-index/blob/master/INDEX#L45

**Review by kmoore134 — APPROVED** [review]

**Comment by justinclift** [comment]
Thanks @kmoore134. :smile:

Just forked that repo and created an [initial commit](https://github.com/justinclift/iocage-plugin-index/commit/591487186bb9134e008d401179abae1f674c457f) with the png → svg change there.  (Not yet a PR).

Looking at the icon files, they seem to be served from "https://icons.freenas.org/community-icons/".

What's the process for adding the svg file there?

Would it also be a good idea to keep the png there as well for a while, in case some people are using older cached versions of the plugin index?

I'll make a PR from the commit once I know. :smile:

**Comment by kmoore134** [comment]
Ahh, you'll want to make a PR to add that svg to here:

https://github.com/ix-plugin-hub/iocage-plugin-index/tree/master/icons

That will sync to that community-icons/ URL automatically once merged into master.

**Comment by justinclift** [comment]
Thanks @kmoore134.

Any idea if the .png file should be left in place for a while longer, in case people are using an older version of the index info?

**Comment by kmoore134** [comment]
Yes, disk space is cheap, and we should keep that .png in place for a while :)

**Comment by justinclift** [comment]
Thanks, will do. :smile:

**Pull request merged**
