### PR TITLE
Update Dependency

### PR DESCRIPTION
**Pull request by miwi-fbsd**

### CODE REVIEW

**Comment by miwi-fbsd** [comment]
> Dont we need an upgrade plan first?

Sent you an invite to the doc, the plugin is atm disable via INDEX. no harm to anyone at this point

**Comment by miwi-fbsd** [comment]
I think for 11.3 we can move it. 11.2 is fine now.

**Comment by william-gr** [comment]
You still need an upgrade script for people coming from 11.2, no?

**Comment by miwi-fbsd** [comment]
no

**Comment by william-gr** [comment]
Please elaborate :)

How are people upgrading from 11.2 version using postgresql 9.5 to 11.3 version using postgresql 11?

**Comment by miwi-fbsd** [comment]
Close https://github.com/freenas/iocage-ix-plugins/pull/148

**Pull request closed without merging**
