### PR TITLE
nextcloud: Update to php8.2

### PR DESCRIPTION
**Pull request by OctopusET**
PR that goes directly into the `13.1-RELEASE` branch
Choose php 8.2 instead of php 8.1

### CODE REVIEW

**Comment by thiagodebugs** [comment]
"php82-pecl-imagick-3.7.0_2" is generating the error "failed to install" when executing the script. I changed it to "php82-pecl-imagick" and it worked perfectly. I recommend the review.

**Review by thiagodebugs — CHANGES_REQUESTED** [review]
"php82-pecl-imagick-3.7.0_2" is generating the error "failed to install" when executing the script. I changed it to "php82-pecl-imagick" and it worked perfectly. I recommend the review.

**Review by sonicaj — COMMENTED** [review]
@OctopusET can you please check @thiagodebugs comment above ? Thanks!

**Comment by OctopusET** [comment]
@sonicaj
I had same issue
Fixed

**Review by sonicaj — APPROVED** [review]

**Pull request merged**
